export const ActionType = {
  FETCH_ABOUT: 'FETCH_ABOUT',
  FETCH_ABOUT_FULFILLED: 'FETCH_ABOUT_FULFILLED',

  FETCH_SERVICE: 'FETCH_SERVICE',
  FETCH_SERVICE_FULFILLED: 'FETCH_SERVICE_FULFILLED',

  FETCH_JOURNEY: 'FETCH_JOURNEY',
  FETCH_JOURNEY_FULFILLED: 'FETCH_JOURNEY_FULFILLED',

  FETCH_PROJECT: 'FETCH_PROJECT',
  FETCH_PROJECT_FULFILLED: 'FETCH_PROJECT_FULFILLED',

  FETCH_TESTIMONIAL: 'FETCH_TESTIMONIAL',
  FETCH_TESTIMONIAL_FULFILLED: 'FETCH_TESTIMONIAL_FULFILLED',

  FETCH_BLOG: 'FETCH_BLOG',
  FETCH_BLOG_FULFILLED: 'FETCH_BLOG_FULFILLED',
};
